// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterPlants.Data;

#nullable disable

namespace WaterPlants.Migrations
{
    [DbContext(typeof(WaterPlantsContext))]
    partial class WaterPlantsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WaterPlants.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LastWatered")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Plant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastWatered = new DateTime(2021, 11, 22, 17, 50, 52, 283, DateTimeKind.Local).AddTicks(8873)
                        },
                        new
                        {
                            Id = 2,
                            LastWatered = new DateTime(2021, 11, 22, 17, 50, 52, 283, DateTimeKind.Local).AddTicks(8908)
                        },
                        new
                        {
                            Id = 3,
                            LastWatered = new DateTime(2021, 11, 22, 17, 50, 52, 283, DateTimeKind.Local).AddTicks(8911)
                        },
                        new
                        {
                            Id = 4,
                            LastWatered = new DateTime(2021, 11, 22, 17, 50, 52, 283, DateTimeKind.Local).AddTicks(8913)
                        },
                        new
                        {
                            Id = 5,
                            LastWatered = new DateTime(2021, 11, 22, 17, 50, 52, 283, DateTimeKind.Local).AddTicks(8915)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
